// <auto-generated />
using System;
using LuxuryHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuxuryHotel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729132717_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuxuryHotel.Models.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBan");

                    b.ToTable("Bans");

                    b.HasData(
                        new
                        {
                            MaBan = "BAN01",
                            TenBan = "Ban Quản Lý"
                        },
                        new
                        {
                            MaBan = "BAN02",
                            TenBan = "Ban Lễ Tân"
                        },
                        new
                        {
                            MaBan = "BAN03",
                            TenBan = "Ban Dịch Vụ & Phòng"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.BinhLuan", b =>
                {
                    b.Property<string>("MaBL")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LuotThich")
                        .HasColumnType("int");

                    b.Property<string>("MaKS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGianDang")
                        .HasColumnType("datetime2");

                    b.HasKey("MaBL");

                    b.HasIndex("MaKS");

                    b.HasIndex("MaPhong");

                    b.ToTable("BinhLuans");

                    b.HasData(
                        new
                        {
                            MaBL = "BL01",
                            LuotThich = 12,
                            MaKS = "KS01",
                            MaPhong = "P101",
                            NoiDung = "Phòng rất sạch đẹp, view biển tuyệt vời!",
                            ThoiGianDang = new DateTime(2026, 3, 15, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaBL = "BL02",
                            LuotThich = 5,
                            MaKS = "KS01",
                            MaPhong = "P102",
                            NoiDung = "Dịch vụ phục vụ rất tận tình chu đáo.",
                            ThoiGianDang = new DateTime(2026, 3, 20, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.ChucVu", b =>
                {
                    b.Property<string>("MaCV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Luong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVus");

                    b.HasData(
                        new
                        {
                            MaCV = "CV01",
                            Luong = 15000000m,
                            TenCV = "Quản lý"
                        },
                        new
                        {
                            MaCV = "CV02",
                            Luong = 8000000m,
                            TenCV = "Lễ tân"
                        },
                        new
                        {
                            MaCV = "CV03",
                            Luong = 6500000m,
                            TenCV = "Nhân viên Phục vụ"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.DichVuPhu", b =>
                {
                    b.Property<string>("MaDVP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DescriptionDVP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDVP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDVP");

                    b.HasIndex("MaKS");

                    b.HasIndex("MaPhong");

                    b.ToTable("DichVuPhus");

                    b.HasData(
                        new
                        {
                            MaDVP = "DVP01",
                            DescriptionDVP = "Buffet sáng Á - Âu cao cấp",
                            Gia = 150000m,
                            MaKS = "KS01",
                            MaPhong = "P101",
                            TenDVP = "Ăn Sáng Buffet",
                            TrangThai = "Hoạt Động"
                        },
                        new
                        {
                            MaDVP = "DVP02",
                            DescriptionDVP = "Thư giãn 60 phút với thảo dược",
                            Gia = 500000m,
                            MaKS = "KS01",
                            MaPhong = "P102",
                            TenDVP = "Dịch Vụ Spa & Massage",
                            TrangThai = "Hoạt Động"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.DonDatPhong", b =>
                {
                    b.Property<string>("MaD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDonDatPhong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaKS");

                    b.HasIndex("MaPhong");

                    b.ToTable("DonDatPhongs");

                    b.HasData(
                        new
                        {
                            MaD = "D01",
                            MaKH = "KH01",
                            MaKS = "KS01",
                            MaPhong = "P101",
                            NgayNhanPhong = new DateTime(2026, 4, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTraPhong = new DateTime(2026, 4, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 2400000m,
                            TrangThaiDonDatPhong = "Đã hoàn thành"
                        },
                        new
                        {
                            MaD = "D02",
                            MaKH = "KH02",
                            MaKS = "KS01",
                            MaPhong = "P102",
                            NgayNhanPhong = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTraPhong = new DateTime(2026, 4, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 2500000m,
                            TrangThaiDonDatPhong = "Đã đặt trước"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaD")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ThoiGianHD")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTienHD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiHD")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaD");

                    b.HasIndex("MaKH");

                    b.ToTable("HoaDons");

                    b.HasData(
                        new
                        {
                            MaHD = "HD01",
                            MaD = "D01",
                            MaKH = "KH01",
                            ThoiGianHD = new DateTime(2026, 4, 3, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            TongTienHD = 2400000m,
                            TrangThaiHD = "Đã Thanh Toán"
                        },
                        new
                        {
                            MaHD = "HD02",
                            MaD = "D02",
                            MaKH = "KH02",
                            ThoiGianHD = new DateTime(2026, 4, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            TongTienHD = 2500000m,
                            TrangThaiHD = "Chưa Thanh Toán"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CCCD_CMND_KH")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            MaKH = "KH01",
                            CCCD_CMND_KH = "034567890123",
                            Email = "customer@luxuryhotel.com",
                            Password = "123456",
                            Phone = "0788811035",
                            TenKH = "Phạm Minh D"
                        },
                        new
                        {
                            MaKH = "KH02",
                            CCCD_CMND_KH = "034567890124",
                            Email = "",
                            Password = "",
                            Phone = "0788811039",
                            TenKH = "Hoàng Thị E"
                        },
                        new
                        {
                            MaKH = "KH03",
                            CCCD_CMND_KH = "034567890125",
                            Email = "",
                            Password = "",
                            Phone = "0788811042",
                            TenKH = "Đỗ Văn F"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.KhachSan", b =>
                {
                    b.Property<string>("MaKS")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DescriptionKS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKS");

                    b.ToTable("KhachSans");

                    b.HasData(
                        new
                        {
                            MaKS = "KS01",
                            DescriptionKS = "Khách sạn nghỉ dưỡng 5 sao sát biển Mỹ Khê.",
                            DiaDiem = "Đà Nẵng",
                            TenKS = "LX Hotel Đà Nẵng"
                        },
                        new
                        {
                            MaKS = "KS02",
                            DescriptionKS = "Tận hưởng không khí biển tươi mát cùng dịch vụ cao cấp.",
                            DiaDiem = "Vũng Tàu",
                            TenKS = "LX Hotel Vũng Tàu"
                        },
                        new
                        {
                            MaKS = "KS03",
                            DescriptionKS = "Khách sạn hiện đại nằm ngay trung tâm thành phố biển.",
                            DiaDiem = "Nha Trang",
                            TenKS = "LX Hotel Nha Trang"
                        },
                        new
                        {
                            MaKS = "KS04",
                            DescriptionKS = "Sang trọng, đẳng cấp tọa lạc tại trung tâm Quận 1.",
                            DiaDiem = "Hồ Chí Minh",
                            TenKS = "LX Hotel Hồ Chí Minh"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CCCD_CMND_NV")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaCV");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaNV = "NV01",
                            CCCD_CMND_NV = "012345678901",
                            MaBan = "BAN01",
                            MaCV = "CV01",
                            SDT = "0901234567",
                            TenNV = "Nguyễn Văn A"
                        },
                        new
                        {
                            MaNV = "NV02",
                            CCCD_CMND_NV = "012345678902",
                            MaBan = "BAN02",
                            MaCV = "CV02",
                            SDT = "0912345678",
                            TenNV = "Trần Thị B"
                        },
                        new
                        {
                            MaNV = "NV03",
                            CCCD_CMND_NV = "012345678903",
                            MaBan = "BAN03",
                            MaCV = "CV03",
                            SDT = "0923456789",
                            TenNV = "Lê Văn C"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DescriptionPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKS")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("SoNguoi")
                        .HasColumnType("tinyint");

                    b.Property<string>("TrangThaiPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaKS");

                    b.ToTable("Phongs");

                    b.HasData(
                        new
                        {
                            MaPhong = "P101",
                            DescriptionPhong = "Phòng hướng biển ban công rộng",
                            Gia = 1200000m,
                            LoaiPhong = "Deluxe Ocean",
                            MaKS = "KS01",
                            SoNguoi = (byte)2,
                            TrangThaiPhong = "Trống"
                        },
                        new
                        {
                            MaPhong = "P102",
                            DescriptionPhong = "Phòng VIP đầy đủ tiện nghi xa hoa",
                            Gia = 2500000m,
                            LoaiPhong = "Suite VIP",
                            MaKS = "KS01",
                            SoNguoi = (byte)4,
                            TrangThaiPhong = "Có Khách"
                        },
                        new
                        {
                            MaPhong = "P201",
                            DescriptionPhong = "Phòng tiêu chuẩn ấm cúng",
                            Gia = 900000m,
                            LoaiPhong = "Standard Double",
                            MaKS = "KS02",
                            SoNguoi = (byte)2,
                            TrangThaiPhong = "Trống"
                        },
                        new
                        {
                            MaPhong = "P301",
                            DescriptionPhong = "Phòng Tổng Thống đẳng cấp bậc nhất",
                            Gia = 5000000m,
                            LoaiPhong = "Presidential Suite",
                            MaKS = "KS03",
                            SoNguoi = (byte)4,
                            TrangThaiPhong = "Thiết Hại"
                        });
                });

            modelBuilder.Entity("LuxuryHotel.Models.BinhLuan", b =>
                {
                    b.HasOne("LuxuryHotel.Models.KhachSan", "KhachSan")
                        .WithMany()
                        .HasForeignKey("MaKS")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxuryHotel.Models.Phong", "Phong")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("LuxuryHotel.Models.DichVuPhu", b =>
                {
                    b.HasOne("LuxuryHotel.Models.KhachSan", "KhachSan")
                        .WithMany()
                        .HasForeignKey("MaKS")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxuryHotel.Models.Phong", "Phong")
                        .WithMany("DichVuPhus")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("LuxuryHotel.Models.DonDatPhong", b =>
                {
                    b.HasOne("LuxuryHotel.Models.KhachHang", "KhachHang")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxuryHotel.Models.KhachSan", "KhachSan")
                        .WithMany()
                        .HasForeignKey("MaKS")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LuxuryHotel.Models.Phong", "Phong")
                        .WithMany("DonDatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("KhachSan");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("LuxuryHotel.Models.HoaDon", b =>
                {
                    b.HasOne("LuxuryHotel.Models.DonDatPhong", "DonDatPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxuryHotel.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDatPhong");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("LuxuryHotel.Models.NhanVien", b =>
                {
                    b.HasOne("LuxuryHotel.Models.Ban", "Ban")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuxuryHotel.Models.ChucVu", "ChucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("LuxuryHotel.Models.Phong", b =>
                {
                    b.HasOne("LuxuryHotel.Models.KhachSan", "KhachSan")
                        .WithMany("Phongs")
                        .HasForeignKey("MaKS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("LuxuryHotel.Models.Ban", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("LuxuryHotel.Models.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("LuxuryHotel.Models.DonDatPhong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("LuxuryHotel.Models.KhachHang", b =>
                {
                    b.Navigation("DonDatPhongs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("LuxuryHotel.Models.KhachSan", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("LuxuryHotel.Models.Phong", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("DichVuPhus");

                    b.Navigation("DonDatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
